package com.dao.daotv.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dao.daotv.dao.dao_celestial;
import com.dao.daotv.sql.Video;

import com.dao.daotv.sql.dao_celestialDao;
import com.dao.daotv.sql.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dao_celestialDaoConfig;
    private final DaoConfig videoDaoConfig;

    private final dao_celestialDao dao_celestialDao;
    private final VideoDao videoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dao_celestialDaoConfig = daoConfigMap.get(dao_celestialDao.class).clone();
        dao_celestialDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        dao_celestialDao = new dao_celestialDao(dao_celestialDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);

        registerDao(dao_celestial.class, dao_celestialDao);
        registerDao(Video.class, videoDao);
    }
    
    public void clear() {
        dao_celestialDaoConfig.clearIdentityScope();
        videoDaoConfig.clearIdentityScope();
    }

    public dao_celestialDao getDao_celestialDao() {
        return dao_celestialDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

}
